# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box Settings
	config.vm.box = "ubuntu/bionic64"

  # Provider Settings
	  config.vm.provider "virtualbox" do |vb|  
		  	# vb.gui = true
			vb.name = "nodejs-box"
			vb.memory = "1024"
			vb.cpus = 1	  
		  end

  # Network Settings
	  config.vm.network "private_network", ip: "192.168.33.100"

  # Folder Settings
	config.vm.synced_folder "C:/Users/murdo/Desktop/Projects/dna-shoebot", "/home/vagrant/dna-shoebot"

  # Provision Settings
# 	config.vm.provision "install-node", type: "shell", privileged: false do |s|
#     s.path = "./provisions.sh"
#   end
  
end
